drivers: thermal: remove C99 comments
ERROR: do not use C99 // comments.
C99 comments are removed in intel_pch_thermal.c

Signed-off-by: Hema prathaban <hemaklnce@gmail.com>